name: Deploy to AWS Lambda
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == ${{ vars.ALLOWED_USER }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    
    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'
    
    - name: Generate Encryption Key
      run: |
        python generatekey.py >> $GITHUB_ENV
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_SECRET }}
        aws-region: ap-northeast-2
    
    - name: Package Lambda function
      run: |
        zip lambdaFunction.zip lambdaFunction.mjs
    
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name kite-auth-adapter --zip-file fileb://lambdaFunction.zip
        aws lambda update-function-configuration --function-name kite-auth-adapter --environment "Variables={ENCRYPTION_KEY=${{ env.ENCRYPTION_KEY }}}"
      env:
        AWS_DEFAULT_REGION: ap-northeast-2
